# Generated by Django 3.2.4 on 2021-06-18 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handbook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('short_name', models.CharField(max_length=10, verbose_name='Короткое наименование')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='HandbookVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=255, verbose_name='Версия')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('handbook_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminology.handbook')),
            ],
        ),
        migrations.CreateModel(
            name='HandbookElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('element_code', models.CharField(max_length=255, verbose_name='Код элемента')),
                ('element_value', models.CharField(max_length=255, verbose_name='Значение элемента')),
                ('handbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminology.handbookversion')),
            ],
        ),
    ]
