# Generated by Django 3.2.4 on 2021-06-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0002_alter_handbookversion_handbook_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handbookelement',
            name='handbook',
        ),
        migrations.AddField(
            model_name='handbookelement',
            name='handbook',
            field=models.ManyToManyField(to='terminology.HandbookVersion'),
        ),
    ]
