# Generated by Django 3.2.4 on 2021-06-18 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0003_auto_20210618_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbookversion',
            name='starting_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
